version: '3.8'

services:
  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - mern-network
    restart: always

  backend:
    container_name: backend-container
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env   # ✅ load backend env automatically
    depends_on:
      - mongo
    networks:
      - mern-network
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: ajio_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network
    restart: always

volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge