// brandsData.js
export const brandsData = {
  men: {
    "Premium Brands": [
      "Vooter",
      "Scotch & Soda",
      "Khushi Creation",
      "LINZA",
      "GANT",
      "Netplay",
      "Yousta",
      "EA7 EMPORIO ARMANI",
    ],
    "Exclusive Brands": [
      "ASOS",
      "BUDA JEANS CO",
      "Levi's",
      "DNMX",
      "Alpha Tribe",
      "Dennis Lingo",
      "Lee Cooper",
      "Armani Exchange",
      "Woxen",
    ],
    "International Brands": [
      "ASOS",
      "French Connection",
      "TOM TAILOR",
      "New Balance",
      "DIESEL",
      "Ooko Kaka",
    ],
    Footwear: [
      "ADIDAS",
      "Campus",
      "Crocs",
      "Nike",
      "Puma",
      "Red Tape",
      "Reebok",
      "Skechers",
      "UCB",
      "Woodland",
    ],
    "Western Wear": [
      "THE INDIAN GARAGE CO",
      "US Polo Assn",
      "LEVIS",
      "LOUIS PHILIPPE",
      "THE BEAR HOUSE",
      "KETCH",
      "DENNISLINGO PREMIUM ATTIRE",
      "Jack & Jones",
      "ALLEN SOLLY",
      "Fort Collins",
      "SPYKAR",
    ],
    Innerwear: ["calvin-klein-underwear", "Jockey"],
    Accessories: ["ADIDAS", "Allen Solly", "F Gear", "LEVIS", "Puma", "Rayban"],
  },

  women: {
    "Premium Brands": [
      "VERO MODA",
      "ONLY",
      "Superdry",
      "Scotch & Soda",
      "GAP",
      "Forever New",
    ],
    "Exclusive Brands": [
      "DNMX",
      "Fig",
      "Fusion",
      "AVAASA",
      "Netplay",
      "Teamspirit",
    ],
    "International Brands": [
      "Levis",
      "Marks & Spencer",
      "Tommy Hilfiger",
      "Calvin Klein",
      "Lacoste",
      "Mango",
    ],
    Ethnicwear: [
      "Biba",
      "W",
      "Aurelia",
      "Soch",
      "Global Desi",
      "Indya",
      "Gulmohar Jaipur",
    ],
    Westernwear: [
      "ONLY",
      "VERO MODA",
      "Kazo",
      "Style Quotient",
      "Forever 21",
      "Sassafras",
    ],
    Footwear: [
      "Catwalk",
      "Mochi",
      "Metro",
      "Bata",
      "Aldo",
      "Clarks",
      "Steve Madden",
    ],
    Accessories: [
      "Fossil",
      "Titan",
      "Caprese",
      "Lavie",
      "Charles & Keith",
      "Guess",
    ],
  },

  kids: {
    "Popular Brands": [
      "Gini & Jony",
      "US Polo Kids",
      "Allen Solly Junior",
      "Mothercare",
      "Pepe Jeans Kids",
      "United Colors of Benetton Kids",
    ],
    "Infant Wear": ["Babyhug", "Carter’s", "Mini Klub", "Mothercare"],
    Boys: [
      "US Polo Assn Kids",
      "Allen Solly Junior",
      "Pepe Jeans",
      "Gini & Jony",
      "Teamspirit Kids",
    ],
    Girls: [
      "Cutecumber",
      "Mothercare",
      "US Polo Assn Kids",
      "Biba Girls",
      "Global Desi Girl",
    ],
    Footwear: ["Crocs", "Nike Kids", "Adidas Kids", "Skechers Kids"],
    Toys: ["Lego", "Hot Wheels", "Barbie", "Fisher Price"],
  },

  beauty: {
    Makeup: [
      "Lakme",
      "Maybelline",
      "L’Oreal",
      "MAC",
      "Revlon",
      "Colorbar",
      "Huda Beauty",
    ],
    Skincare: [
      "Biotique",
      "Lotus Herbals",
      "Neutrogena",
      "Forest Essentials",
      "Mamaearth",
      "WOW",
    ],
    Haircare: [
      "L’Oreal Professional",
      "Tresemme",
      "Matrix",
      "Head & Shoulders",
      "Dove",
      "WOW",
    ],
    Fragrances: [
      "Davidoff",
      "Calvin Klein",
      "Gucci",
      "Versace",
      "The Body Shop",
      "Yves Saint Laurent",
    ],
    "Bath & Body": [
      "The Body Shop",
      "Nivea",
      "Dove",
      "Palmolive",
      "Biotique",
      "Bath & Body Works",
    ],
    "Men’s Grooming": [
      "Beardo",
      "The Man Company",
      "Bombay Shaving Company",
      "Ustraa",
      "Park Avenue",
    ],
    "Beauty Tools": ["Vega", "Philips", "Dyson", "Braun"],
  },

  "home-kitchen": {
    "Home Furnishing": [
      "Spaces",
      "Portico",
      "Bombay Dyeing",
      "D’Decor",
      "Story@Home",
    ],
    Decor: [
      "Home Centre",
      "Chumbak",
      "Good Earth",
      "India Circus",
      "Random",
    ],
    Kitchenware: ["Prestige", "Pigeon", "Butterfly", "Hawkins", "Wonderchef"],
    Appliances: [
      "Philips",
      "Bajaj",
      "Morphy Richards",
      "Usha",
      "Panasonic",
    ],
    Furniture: [
      "Urban Ladder",
      "Pepperfry",
      "HomeTown",
      "Nilkamal",
      "Godrej Interio",
    ],
    Lighting: ["Philips", "Wipro", "Syska", "Havells"],
  },
};
